config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'website#index'
get "/login", to: "sessions#new"
post "/sessions", to: "sessions#create"
get "/logout", to: "sessions#destroy"
get 'about', to: 'static#about'
get 'services', to: 'static#services'
get 'contact', to: 'static#contact'
get '/auth/google_oauth2/callback' => 'sessions#omniauth'


resources :users, only: [:create, :new, :edit, :show] do
  resources :shopping_lists, only: [:index, :new, :create]
end

resources :shopping_lists, only: [:edit, :update, :show, :destroy] do
  resources :items
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :user , optional: true
    belongs_to :store, optional: true
    belongs_to :shopping_list, optional: true

    validates :name, presence: true
    validates :price, presence: true
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
    belongs_to :user, counter_cache: true
    belongs_to :store
    has_many :items

    validates :name, presence: true
    validates :budget, presence: true
    validates :budget, numericality: {greater_than_or_equal_to: 0}
    scope :recent, -> { order("created_at DESC") }
end

app/models/store.rb
class Store < ApplicationRecord
    has_many :shopping_lists
    has_many :users, through: :shopping_lists
    

    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :shopping_lists
    has_many :stores, through: :shopping_lists
    has_many :items, through: :shopping_lists
    has_secure_password

    validates :username, { :length => { :minimum => 2 } }
    validates :email, presence: true
    validates :email, uniqueness: true
    validates :password, { :length => { :in => 4..16 } }

    
    def self.from_omniauth(auth)
        where(email: auth.info.email).first_or_initialize do |user|
          user.username = auth.info.name
          user.email = auth.info.email
          user.password = SecureRandom.hex(8)
        end
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception
    helper_method :current_user

    def require_login
        if !logged_in?
            redirect_to login_path
        end
    end

    def logged_in?
        !!current_user
    end

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

   


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_shopping_list, only: [:show, :create, :edit, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def show
      
  end

  def edit
      
  end

  def create
    set_shopping_list
    @item = @list.items.create(item_params)
    redirect_to shopping_list_path(@list)
end

  def update
       
      if @item.update(item_params)
        redirect_to shopping_list_path(@list)
      else
        #flash message
        render 'edit'
      end
  end

    def index
      if current_user && params[:shopping_list_id].present?
        @list = ShoppingList.find_by(id: params[:shopping_list_id])
        #@user = current_user
        @items = Shopping_list.items.all
      else
        redirect_to user_shopping_lists_path
      end
    end

    def destroy
      
      @item.destroy
      
      redirect_to @list, notice: "Item removed."
    end


    private
    def item_params
        params.require(:item).permit(:name, :price, :user_id, :store_id, :shopping_list_id)
    end

    def set_shopping_list
        @list = ShoppingList.find(params[:shopping_list_id])
    end

    def set_item
        @item = @list.items.find(params[:id])
    end

    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to user_shopping_lists_path(@user)
        else 
            @user.errors.add(:password, :invalid, message: "is inccorect")
            render '/sessions/new'
        end
    end

    def destroy
        reset_session
        redirect_to login_path
      end

      def omniauth
        @user = User.from_omniauth(auth)
        if @user.save
        session[:user_id] = @user.id
        redirect_to @user
        else
          redirect_to new_user_path
        end
      end


      private

      def auth
        request.env['omniauth.auth']
      end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :require_login
  before_action :set_list, only: [:edit, :update, :destroy, :show]

  def index
    if params[:user_id].present?
      @user = current_user
      @lists = current_user.shopping_lists.all.recent.paginate(page: params[:page], per_page: 3)      
    else
      redirect_to user_shopping_lists_path
    end
  end


  def show
  end
  

  def new
    @list = current_user.shopping_lists.build
  end

  def create
    @list = ShoppingList.new(list_params)

    if @list.save
      redirect_to shopping_list_path(@list)
    else
      render :new
    end
  end

  def edit
    
    @user = current_user
    
  end

  def update
    @user = current_user
    @list.update(list_params)
    redirect_to shopping_list_path(@list)
  end

  def destroy
    @list = ShoppingList.find(params[:id])
    @list.destroy
    redirect_to user_shopping_lists_path(current_user)
  end

  private
  def list_params
    params.require(:shopping_list).permit(:name, :budget, :store_id, :user_id)
  end

  def set_list
    @list = ShoppingList.find(params[:id])
  end

  

end

app/controllers/static_controller.rb
  
class StaticController < ApplicationController

    def about
        
    end

    def services
        
    end

    def contact
        
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only:[:edit, :show, :update, :destroy]

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            #raise params.inspect
            redirect_to user_path(@user)
        else
            render 'users/new'
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password, :admin, :shopping_lists_count)  
    end

end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  
  def index
    if current_user
      redirect_to user_shopping_lists_path(current_user.id)
    else
      render :index
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/website_helper.rb
module WebsiteHelper
end

app/views/items/_form.html.erb
<%= form_with(model: [ @list, item ], local: true) do |f| %>
    <p>
        <%=f.hidden_field "shopping_list_id", value: @list.id  %>
        <%=f.hidden_field "user_id", value: @list.user_id  %>
        <%=f.hidden_field "store_id", value: @list.store_id  %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :price %>
        <%= f.text_field :price, value: item.price%>
    </p>
    <p> <%=f.submit %> </p>
    <% end %>

app/views/items/_item.html.erb
<label> 
    <strong>
    
<%= link_to item.name, edit_shopping_list_item_path(@list, item)  %> | <%= item.price%> 
    </strong>
</label>

<label> Edit this product:</label>

<%= render 'items/form', item: item %>

<p> <%= button_to "REMOVE ITEM", shopping_list_item_path(@list, item), method: :delete %> </p>

<hr>

app/views/items/edit.html.erb
<p id="notice"> <%=notice%> </p>

<p>
    Editing Product <%=@item.name%>
</p>

<%= render 'items/form', item: @item  %>

app/views/items/index.html.erb
<h1>Shopping List Items</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopilator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  </head>

  <body>

    <div class='wrapper'>
      <%= yield %>
    </div>
    
  </body>

</html>

app/views/partials/_header.html.erb
<% if current_user %>
    
    <nav>
        
        <input type="checkbox" id="check">
        
        <label for="check" class="checkbtn">
            <i class="fa fa-bars"></i>
        </label>
            
        <img src="https://i.ibb.co/GWnZgd2/shopilator-logo-wht-nobkg.png" id="logoimg">
        <label class="user-title"><%=current_user.username%></label>

            <ul>
                <li> <%= link_to "Account", user_path(current_user), class: "header-link"%></a></li>
                <li><a href="/" class="header-link">My Lists</a></li>
                <li><%= link_to "Create A New List", new_user_shopping_list_path(current_user, @list), class: "header-link" %></li>
                <li><a href="/" class="header-link">Contact</a></li>
                <li><a href="/logout" class="header-link">Logout</a></li>
            </ul>
    </nav>
    <% else %>
        <nav>
            <input type="checkbox" id="check">
            <label for="check" class="checkbtn">
                <i class="fa fa-bars"></i>
            </label>
            <img src="https://i.ibb.co/GWnZgd2/shopilator-logo-wht-nobkg.png" id="logoimg">
                <ul>
                    <li> <a href="/" class="header-link">Home</a></li>
                    <li><a href="/about" class="header-link">About Us</a></li>
                    <li><a href="/services" class="header-link">Services</a></li>
                    <li><a href="/contact" class="header-link">Contact</a></li>
                    <li><a href="/login" class="header-link">Login</a></li>
                </ul>
        </nav>
    <% end %>

app/views/shopping_lists/edit.html.erb
<%= form_for @list, url: shopping_list_url do |f| %>
<div style="color:white">
        <% if @list.errors.any? %>
            <label style="font-weight: bold">Oops, we hit a snag!</label>
            <ul>
                <% @list.errors.full_messages.each do |message| %>
                <li style="font-size: 12px; text-align: left; "><%= message %></li>
                <% end %>
            </ul>
            <% end %>
        </div>
  
    <%= f.hidden_field "user_id", value: current_user.id  %>
    <%= f.text_field :name, value: @list.name %> <br>
    <%= f.number_field :budget, value: @list.budget %> <br>

    
  <%= collection_select(:shopping_list, :store_id, Store.all,
                  :id, :name,
                 {:prompt => 'Please select a Store'}) %> <br>
 
        
        <%= f.submit "CREATE", class: "signup-btn"%><br>
        <% end %>

app/views/shopping_lists/index.html.erb
<%= render 'partials/header'%>

<h1>Shopping Lists:</h1>


    <% @lists.each do |list| %>

    <table id="list-table" >
        <tr id="list-tr" >
            <td class="list-td" id="date">
                <label id="month-day"><%= list.created_at.strftime("%b %d") %></label><br>
                <label id="year"><%= list.created_at.strftime("%Y") %></label>
            </td>
            <td class="list-td" id="details"> 
                <label ><a id="list-name" href="/shopping_lists/<%=list.id%>"><%=list.name%></a></label>
                <label> <a href="/" class="view-item-list"></a></label><br>
                <label id="store-name"><%= list.store.name + " - Budget: $" + list.budget.to_s %></label>
            </td> 
            <td class="list-td" id="budget">
                <% if list.items.sum(:price) == 0 %>
                    <label class="no-total">No Items Added</label>
                <% elsif list.budget >= list.items.sum(:price) %>
                    <label class="total" style="color:green">$<%= list.items.sum(:price).truncate(2) %></label><br>
                    <label id="store-name">+<%= (list.budget - list.items.sum(:price)).truncate(2) %> saved</label>
                <% elsif list.budget < list.items.sum(:price) %>
                    <label class="total" style="color:red">$<%= list.items.sum(:price).truncate(2) %></label><br>
                    <label id="store-name">-<%= (list.items.sum(:price) - list.budget).truncate(2) %> over budget </label>
                <% end %>
                    
            </td>
            <td class="list-td" id="list-options">
                <label><%= button_to "EDIT", edit_shopping_list_path(list), method: :get, id: "edit-list" %></label><br> 
                <label><%= button_to "DELETE", shopping_list_path(list), method: :delete, id: "delete-list" %> </label>
            </td>  
        </tr>
    </table>
    <% end %>

<br>
<br>

<%= will_paginate @lists, previous_label: "< Newest",
    next_label: "Older >", inner_window: 1, outer_widow: 0, class: "list-pages"%>

<%= link_to "Create A New List", new_user_shopping_list_path, id:"create"%>

app/views/shopping_lists/new.html.erb
<h1>ShoppingLists#new</h1>
<%= form_for @list, url: user_shopping_lists_path  do |f| %>
<div style="color:white">
        <% if @list.errors.any? %>
            <label style="font-weight: bold">Oops, we hit a snag!</label>
            <ul>
                <% @list.errors.full_messages.each do |message| %>
                <li style="font-size: 12px; text-align: left; "><%= message %></li>
                <% end %>
            </ul>
            <% end %>
        </div>
  
    <%= f.hidden_field "user_id", value: current_user.id  %>
    <%= f.text_field :name, placeholder: "Shopping List Name" %> <br>
    <%= f.text_field :budget, placeholder: "0.00"  %> <br>

    
  <%= collection_select(:shopping_list, :store_id, Store.all,
                  :id, :name,
                 {:prompt => 'Please select a Store'}) %> <br>
 
        
        <%= f.submit "CREATE", class: "signup-btn"%><br>

<% end %>

app/views/shopping_lists/show.html.erb
<%= render 'partials/header'%>

<label><%= notice %> </label>

<h1><%=@list.name%></h1>

<h2 class="list-td">
BUDGET: 
    <% if @list.budget >= @list.items.sum(:price) %>
        <label style="color:green">$<%= @list.budget %></label>
    <% elsif @list.budget < @list.items.sum(:price) %>
        <label style="color:red">$<%= @list.budget %></label>
    <% end %>
        
</h2>

<% if @list.items.any? %>
    <%= render @list.items %><br>
    <label> <strong> TOTAL: <%= @list.items.sum(:price).truncate(2) %> </strong></label>
    <% end %> <br><br>

<Label>ADD ITEM:</Label>
<%= render 'items/form', item: @list.items.build %>

<%= link_to "Edit Shopping List details", edit_shopping_list_path(@list)%> |
<%= link_to "Back", user_shopping_lists_path(current_user)%>

app/views/stores/_store.html.erb
<label> <%= store.name %> </label><br>

app/views/users/new.html.erb
<div class="signup-form">
    <img src="https://i.ibb.co/BC91qF6/shopilator-green-nobkg.png" class="auth-img">
            <h1>Better Manage Your Grocery Time!</h1>
            <p> <strong>Create an account on Shopilator to access free budegeting tools.</strong> </p>

    <%= form_for @user do |f| %>
        <div style="color:red">
        <% if @user.errors.any? %>
            <label style="font-weight: bold">Oops, we hit a snag!</label>
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                <li style="font-size: 12px; text-align: left; "><%= message %></li>
                <% end %>
            </ul>
            <% end %>
        </div>

        <%= f.text_field :username, placeholder: "Name", class: "input-box"%> <br>
        <%= f.email_field :email, placeholder: "Email", class: "input-box"%> <br>
        <%= f.password_field :password, placeholder: "Password", class: "input-box" %> <br>
        <%= f.submit "Get Started", class: "signup-btn"%><br>
        <hr>
            <p class="or">OR</p><br>
            <%= link_to " Sign up with Google ", '/auth/google_oauth2', class: "google-btn" %><br><br>
            <p class="has-acount"> Already have and account? <%= link_to "LOGIN", login_path %> </p>

    <% end %>
</div>

app/views/users/show.html.erb
<%= render 'partials/header'%>


<h1>Account Settings: <%= @user.username %> </h1>

<%if @user.shopping_lists_count > 0 %>
    <label> <strong>Total Shopping Lists:</strong> <%= @user.shopping_lists_count %></label>
    <br><br>
    <label>
        <strong>Where you shop:</strong>
    </label><br>
    <%= render @user.stores.uniq %>
    
<% else %>
    <label> You haven't created any shopping lists yet</label>
<% end %>

app/views/website/index.html.erb
<%= render 'partials/header'%>

<div id="welcome-container">
    <section id="left">
        <label class="title">Shopilator</label>
        <h1 id="subtitle">Manage Your Grocery Time Better.</h1>
    </section>
    <section id="right">
    <img src="https://i.ibb.co/BC91qF6/shopilator-green-nobkg.png" id="welcome-logo-r">
            <p> <strong>Create an account on Shopilator to access free budegeting tools.</strong> </p>

            <button type='button' class="signup-btn" ><%=link_to "Create an Account", new_user_path %></button><br>
            

    </section>
        
</div> <!--End of Welcome Container-->
        




<!--LOGO LINKS:
https://i.ibb.co/BC91qF6/shopilator-green-nobkg.png
https://i.ibb.co/yWPrvsQ/shopilator-logo.png
https://i.ibb.co/GWnZgd2/shopilator-logo-wht-nobkg.png

-->